import streamlit as st


def render_footer():

    footer_html = """
    <div class="trustloan-footer">

        <div class="footer-brand">
            TRUSTLOAN AI
            <span>·</span>
            Intelligent Loan Eligibility Prediction
        </div>

        <div class="footer-divider"></div>

        <div class="footer-disclaimer">
            Academic Machine Learning Prototype
        </div>

        <div class="footer-note">
            Predictions are estimates generated by a machine-learning model
            and should not be treated as actual lending decisions.
        </div>

        <div class="footer-tech">
            Explainable AI
            <span>·</span>
            SHAP
            <span>·</span>
            Machine Learning
        </div>

    </div>
    """

    st.html(footer_html)